# Permalinks
permalink:           pretty

# Setup
title:               Bradley Tjandra
tagline:             Sydney, Australia
url:                 https://bradleytjandra.github.io/
#paginate:            1
baseurl:             ''
markdown:            kramdown

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Bradley Tjandra 
  url:               https://twitter.com/BradleyTjandra
  email:             bjtjandra@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/BradleyTjandra/BradleyTjandra.github.io

# Gems
gems:
#  - jekyll-paginate
  - jekyll-gist

# This is the list of pages to incldue in the header of the website.
pages_list: {'About':'/about','Archive':'/archive','Feed':'/atom.xml'}
